export type Interaction = "Offline" | "Passive" | "Active";
export type DataPath = "Local" | "External" | "Mixed";
export type Setup = "Easy" | "Moderate" | "Advanced";

export type Tool = {
  name: string;
  category: string;
  summary: string;
  repo: string;
  keywords: string;
  interaction: Interaction;
  data: DataPath;
  setup: Setup;
  delivery: string;
  platforms: string[];
  output: string;
  limitation: string;
  evidence: "Repository verified";
  reviewed: string;
};

type Row = [string, string, string, string, string, Interaction, DataPath, Setup, string, string, string, string];

const rows: Row[] = [
  ["CyberChef","Data analysis","Transform, decode and inspect text or binary data through repeatable browser recipes.","gchq/CyberChef","decode base64 xor hashes url email header","Offline","Local","Easy","Browser","Windows, macOS, Linux","Files, text, recipes","Complex recipes still require analyst validation."],
  ["jq","Data analysis","Query and reshape JSON evidence from scripts, APIs and exported logs.","jqlang/jq","json query parse transform logs","Offline","Local","Easy","CLI","Windows, macOS, Linux","JSON, text","Not a security-specific parser."],
  ["ripgrep","Data analysis","Search large evidence collections quickly with regular expressions and file filters.","BurntSushi/ripgrep","search regex logs text evidence","Offline","Local","Easy","CLI","Windows, macOS, Linux","Matched text","Search quality depends on the query."],
  ["Timesketch","Timeline analysis","Collaboratively analyse forensic timelines and large event datasets.","google/timesketch","timeline forensic events collaborative","Offline","Local","Advanced","Web platform","Linux","Timelines, tags, reports","Requires server infrastructure and ingestion planning."],
  ["Plaso","Timeline analysis","Extract timestamps from many artefact types into a forensic super-timeline.","log2timeline/plaso","timeline log2timeline forensic timestamps","Offline","Local","Advanced","CLI","Windows, macOS, Linux","Timeline storage","Parsing can be resource intensive."],
  ["Chainsaw","Windows forensics","Search Windows forensic artefacts and hunt event logs with Sigma logic.","WithSecureLabs/chainsaw","windows event logs evtx sigma hunt","Offline","Local","Moderate","CLI","Windows, macOS, Linux","JSON, CSV, text","Rule coverage and event quality determine results."],
  ["Hayabusa","Windows forensics","Create fast timelines and threat-hunting results from Windows event logs.","Yamato-Security/hayabusa","windows event logs evtx timeline sigma","Offline","Local","Moderate","CLI","Windows, macOS, Linux","CSV, JSON, timeline","Tuning is needed to control false positives."],
  ["Eric Zimmerman Tools","Windows forensics","Parse common Windows forensic artefacts with a focused suite of utilities.","EricZimmerman/Get-ZimmermanTools","windows registry mft prefetch shellbags forensic","Offline","Local","Moderate","Desktop + CLI","Windows","CSV, JSON, reports","A toolkit rather than one unified workflow."],
  ["KAPE","Evidence collection","Collect and process targeted Windows forensic artefacts using configurable targets.","EricZimmerman/KapeFiles","windows collection triage targets modules","Offline","Local","Moderate","CLI","Windows","Collected artefacts","Collection must be authorised and scoped."],
  ["DFIR ORC","Evidence collection","Reliably collect forensic artefacts from Windows systems at scale.","DFIR-ORC/dfir-orc","windows collection registry mft event logs","Active","Local","Advanced","CLI","Windows","Archives, XML","Deployment and configuration require care."],
  ["Velociraptor","Endpoint visibility","Collect and query endpoint artefacts at scale for hunting and response.","Velocidex/velociraptor","endpoint dfir vql collection hunt","Active","Mixed","Advanced","Server + client","Windows, macOS, Linux","Collections, notebooks","Powerful queries can affect endpoints if misused."],
  ["GRR","Endpoint visibility","Perform remote live forensics and targeted endpoint collection.","google/grr","remote live forensics endpoint collection","Active","Mixed","Advanced","Server + client","Windows, macOS, Linux","Collected artefacts","Needs secured infrastructure and operator controls."],
  ["osquery","Endpoint visibility","Query operating-system state using SQL-shaped tables.","osquery/osquery","endpoint sql processes users files configuration","Active","Local","Moderate","Agent + CLI","Windows, macOS, Linux","Tables, JSON","Continuous deployment needs fleet management."],
  ["Fleet","Endpoint visibility","Manage osquery fleets, policies and endpoint visibility through a central service.","fleetdm/fleet","osquery fleet endpoint policy inventory","Active","Mixed","Advanced","Web platform","Windows, macOS, Linux","Queries, inventory","Centralisation creates sensitive operational data."],
  ["Volatility 3","Memory forensics","Extract processes, network artefacts and evidence from memory images.","volatilityfoundation/volatility3","memory ram malware process forensic","Offline","Local","Advanced","CLI","Windows, macOS, Linux","Text, JSON","Symbol availability and acquisition quality matter."],
  ["MemProcFS","Memory forensics","Expose memory images through a virtual file system for rapid analysis.","ufrisk/MemProcFS","memory virtual filesystem process forensic","Offline","Local","Advanced","CLI + mount","Windows, Linux","Mounted artefacts","Kernel and symbol knowledge may be required."],
  ["LiME","Memory acquisition","Acquire volatile memory from Linux systems as a loadable kernel module.","504ensicsLabs/LiME","linux memory acquisition ram kernel","Active","Local","Advanced","Kernel module","Linux","Memory image","Loading a module changes the live system."],
  ["AVML","Memory acquisition","Acquire physical memory from Linux systems with a portable user-space tool.","microsoft/avml","linux memory acquisition ram","Active","Local","Moderate","CLI","Linux","Memory image","Live acquisition affects the system being captured."],
  ["Autopsy","Disk forensics","Examine disk images and file-system evidence through a graphical workflow.","sleuthkit/autopsy","disk image filesystem deleted files forensic","Offline","Local","Moderate","Desktop","Windows, macOS, Linux","Case database, reports","Large cases require substantial storage."],
  ["The Sleuth Kit","Disk forensics","Analyse file systems and disk images with composable command-line tools.","sleuthkit/sleuthkit","disk filesystem image forensic deleted","Offline","Local","Advanced","CLI + library","Windows, macOS, Linux","Text, body files","CLI workflows have a steeper learning curve."],
  ["Dissect","Disk forensics","Parse and access many disk, volume and operating-system artefacts in Python.","fox-it/dissect","disk forensic parser windows linux artefacts","Offline","Local","Advanced","Python toolkit","Windows, macOS, Linux","Structured artefacts","Best suited to code-driven investigations."],
  ["bulk_extractor","Disk forensics","Extract features such as emails and URLs from images without file-system parsing.","simsong/bulk_extractor","disk image email url feature carving","Offline","Local","Moderate","CLI","Windows, macOS, Linux","Feature files, histograms","Extracted context can be limited."],
  ["PhotoRec","File recovery","Recover files from damaged media using signature-based carving.","cgsecurity/testdisk","file recovery carving disk media","Offline","Local","Moderate","CLI","Windows, macOS, Linux","Recovered files","Carved files may lose names and paths."],
  ["Wireshark","Network analysis","Inspect packet captures and protocol behaviour with deep filtering.","wireshark/wireshark","pcap packets protocol traffic capture","Offline","Local","Easy","Desktop","Windows, macOS, Linux","PCAP analysis","Live capture can expose sensitive traffic."],
  ["Zeek","Network analysis","Generate rich protocol logs and behavioural telemetry from network traffic.","zeek/zeek","network protocol logs pcap telemetry ids","Passive","Local","Advanced","Sensor + CLI","Linux, macOS","Structured logs","High-volume deployments need tuning and storage."],
  ["Suricata","Network detection","Inspect network traffic with signatures, protocol analysis and file extraction.","OISF/suricata","ids ips network signatures pcap eve","Passive","Local","Advanced","Sensor","Windows, macOS, Linux","EVE JSON, alerts","Rules and inline modes require careful tuning."],
  ["Arkime","Network analysis","Capture, index and search packet metadata with retained packet access.","arkime/arkime","packet capture search session network","Passive","Local","Advanced","Web platform","Linux","Sessions, PCAP","Retention creates significant storage and privacy obligations."],
  ["Brim","Network analysis","Explore Zeek logs and packet-derived data with the Zed query language.","brimdata/brim","zeek pcap zed network query","Offline","Local","Moderate","Desktop + CLI","Windows, macOS, Linux","Queries, exports","Requires familiarity with the underlying data model."],
  ["Sniffnet","Network analysis","Visualise and inspect network traffic locally through a cross-platform interface.","GyulyVGC/sniffnet","network traffic monitor protocol visualisation","Passive","Local","Easy","Desktop","Windows, macOS, Linux","Traffic summaries","Designed for visibility rather than full packet forensics."],
  ["RITA","Network detection","Identify beaconing and unusual communication patterns in Zeek logs.","activecm/rita","beacon c2 zeek network detection","Offline","Local","Moderate","CLI","Linux","Scores, reports","Findings require contextual validation."],
  ["Malcolm","Network analysis","Bundle network traffic analysis, capture and search components into one platform.","cisagov/Malcolm","zeek suricata arkime network traffic","Passive","Local","Advanced","Web platform","Linux","Dashboards, alerts","Resource requirements are substantial."],
  ["tcpdump","Network capture","Capture and inspect network packets from the command line.","the-tcpdump-group/tcpdump","packet capture pcap network cli","Passive","Local","Moderate","CLI","macOS, Linux","PCAP, text","Capture filters and privileges need care."],
  ["Nmap","Network discovery","Discover hosts, services and exposure on authorised networks.","nmap/nmap","ports services hosts discovery scan","Active","Local","Moderate","CLI + GUI","Windows, macOS, Linux","XML, text","Active probing can trigger controls and disrupt fragile systems."],
  ["Masscan","Network discovery","Perform very high-speed TCP port discovery across large address ranges.","robertdavidgraham/masscan","fast port scan network discovery","Active","Local","Advanced","CLI","Windows, macOS, Linux","Lists, JSON, XML","Unsafe rates can overwhelm networks and trigger alerts."],
  ["RustScan","Network discovery","Rapidly identify open ports and hand results to Nmap for deeper inspection.","bee-san/RustScan","ports nmap fast discovery","Active","Local","Moderate","CLI","Windows, macOS, Linux","Open ports","Still produces active network traffic."],
  ["ZMap","Internet measurement","Run large-scale single-packet network measurements for authorised research.","zmap/zmap","internet scan measurement ports","Active","Local","Advanced","CLI","Linux","CSV, JSON","Requires explicit scope, rate control and legal review."],
  ["Amass","Attack-surface discovery","Map external assets using passive sources and optional active enumeration.","owasp-amass/amass","subdomain dns asset discovery osint","Active","External","Advanced","CLI","Windows, macOS, Linux","Graphs, lists","Source terms, API keys and active modes vary."],
  ["Subfinder","Attack-surface discovery","Discover subdomains from passive online sources.","projectdiscovery/subfinder","subdomain passive dns osint","Passive","External","Moderate","CLI","Windows, macOS, Linux","Host lists","Coverage depends on third-party sources."],
  ["dnsx","Attack-surface discovery","Resolve and probe DNS records in bulk with controlled inputs.","projectdiscovery/dnsx","dns resolve record subdomain","Active","External","Moderate","CLI","Windows, macOS, Linux","JSON, host lists","Bulk queries may be logged or rate-limited."],
  ["httpx","Attack-surface discovery","Probe authorised web services and collect response metadata at scale.","projectdiscovery/httpx","http probe web title technology","Active","External","Moderate","CLI","Windows, macOS, Linux","JSON, text","Directly contacts target infrastructure."],
  ["Katana","Web crawling","Crawl authorised web applications and discover endpoints.","projectdiscovery/katana","crawler endpoints javascript web","Active","External","Moderate","CLI","Windows, macOS, Linux","URLs, JSON","Crawling can submit requests at scale."],
  ["SpiderFoot","OSINT","Automate collection and correlation across many OSINT data sources.","smicallef/spiderfoot","osint domain ip email correlation","Passive","External","Moderate","Web + CLI","Windows, macOS, Linux","Graph, reports","Queries are disclosed to configured sources."],
  ["recon-ng","OSINT","Run modular web reconnaissance in a structured workspace.","lanmaster53/recon-ng","osint reconnaissance domain contacts","Passive","External","Moderate","CLI","Windows, macOS, Linux","Database, reports","Modules and external APIs vary in reliability."],
  ["theHarvester","OSINT","Collect public emails, names, hosts and related data from online sources.","laramies/theHarvester","email domain osint hosts search","Passive","External","Easy","CLI","Windows, macOS, Linux","Lists, reports","Public sources may be incomplete or inaccurate."],
  ["Maigret","Identity OSINT","Check username presence across public sites.","soxoj/maigret","username account osint identity","Passive","External","Easy","CLI","Windows, macOS, Linux","HTML, JSON, CSV","Matches can belong to different people."],
  ["Sherlock","Identity OSINT","Search public services for accounts using a supplied username.","sherlock-project/sherlock","username account osint social","Passive","External","Easy","CLI","Windows, macOS, Linux","Text, CSV","Results require identity verification."],
  ["ExifTool","Metadata analysis","Read and edit metadata across a wide range of file formats.","exiftool/exiftool","exif metadata image document gps","Offline","Local","Moderate","CLI","Windows, macOS, Linux","Text, metadata","Editing evidence can compromise forensic integrity."],
  ["YARA","Detection engineering","Describe and match textual or binary patterns in files and memory.","VirusTotal/yara","malware file pattern rule signature","Offline","Local","Moderate","CLI + library","Windows, macOS, Linux","Matches","Poor rules can be noisy or expensive."],
  ["YARA-X","Detection engineering","Use a modern YARA implementation for malware pattern matching.","VirusTotal/yara-x","malware yara rules pattern","Offline","Local","Moderate","CLI + library","Windows, macOS, Linux","Matches","Compatibility and maturity should be checked per release."],
  ["Sigma","Detection engineering","Define portable detection rules for log events across SIEM platforms.","SigmaHQ/sigma","siem logs detection rules","Offline","Local","Moderate","Rules","Platform independent","YAML rules","Translation does not guarantee equivalent backend behaviour."],
  ["pySigma","Detection engineering","Parse, transform and convert Sigma rules with backend plugins.","SigmaHQ/pySigma","sigma convert rules backend","Offline","Local","Advanced","Python library","Windows, macOS, Linux","Backend queries","Backend support and pipelines differ."],
  ["Sigma CLI","Detection engineering","Validate and convert Sigma rules from a command-line workflow.","SigmaHQ/sigma-cli","sigma validate convert rules","Offline","Local","Moderate","CLI","Windows, macOS, Linux","Queries, validation","Requires appropriate backend plugins."],
  ["Chainsaw Rules","Detection content","Apply community Sigma and artefact rules with Chainsaw workflows.","WithSecureLabs/chainsaw","sigma detection content windows","Offline","Local","Moderate","Rules + CLI","Windows, macOS, Linux","Matches","Community content needs local tuning."],
  ["Falco","Cloud-native detection","Detect suspicious runtime behaviour in Linux hosts and containers.","falcosecurity/falco","runtime kubernetes container linux detection","Active","Local","Advanced","Sensor","Linux","Alerts","Kernel integration and rules need operational tuning."],
  ["Tetragon","Cloud-native detection","Observe and enforce Linux and Kubernetes behaviour using eBPF.","cilium/tetragon","ebpf kubernetes runtime security","Active","Local","Advanced","Sensor","Linux","Events, policies","Enforcement can disrupt workloads if misconfigured."],
  ["Tracee","Cloud-native detection","Trace Linux runtime activity and detect suspicious behaviour with eBPF.","aquasecurity/tracee","ebpf runtime container linux forensic","Active","Local","Advanced","CLI + sensor","Linux","JSON, events","Kernel support and event volume vary."],
  ["Trivy","Vulnerability scanning","Scan containers, filesystems, repositories and infrastructure configuration.","aquasecurity/trivy","container vulnerability sbom iac secret","Offline","Mixed","Easy","CLI","Windows, macOS, Linux","SARIF, JSON, SBOM","Fresh vulnerability databases require downloads."],
  ["Grype","Vulnerability scanning","Find known vulnerabilities in container images and filesystems.","anchore/grype","container vulnerability image sbom","Offline","Mixed","Easy","CLI","Windows, macOS, Linux","JSON, SARIF, table","Results depend on package identification and feed freshness."],
  ["Syft","Software inventory","Generate software bills of materials from images and filesystems.","anchore/syft","sbom packages container inventory","Offline","Local","Easy","CLI","Windows, macOS, Linux","CycloneDX, SPDX, JSON","Inventory is not itself a vulnerability assessment."],
  ["Clair","Vulnerability scanning","Index container contents and match packages against vulnerability data.","quay/clair","container image vulnerability scanner","Offline","Mixed","Advanced","Service","Linux","API findings","Requires maintained services and databases."],
  ["TruffleHog","Secret scanning","Find verified and unverified credentials in repositories and other sources.","trufflesecurity/trufflehog","secret credentials git scan","Active","Mixed","Moderate","CLI","Windows, macOS, Linux","JSON, findings","Verification may contact external services."],
  ["Gitleaks","Secret scanning","Detect hard-coded secrets in Git repositories and files.","gitleaks/gitleaks","secret git repository credentials","Offline","Local","Easy","CLI","Windows, macOS, Linux","JSON, SARIF, CSV","Pattern matches require triage."],
  ["detect-secrets","Secret scanning","Create and audit baselines for secrets in source code.","Yelp/detect-secrets","secret source code baseline","Offline","Local","Easy","CLI","Windows, macOS, Linux","JSON baseline","Baseline review remains a human task."],
  ["Semgrep","Static analysis","Scan source code with configurable semantic rules across many languages.","semgrep/semgrep","sast source code rules secure coding","Offline","Mixed","Moderate","CLI + service","Windows, macOS, Linux","SARIF, JSON","Some features and rules rely on hosted services."],
  ["CodeQL","Static analysis","Model code as data and query for vulnerabilities and dangerous patterns.","github/codeql","sast code query vulnerability","Offline","Local","Advanced","CLI + queries","Windows, macOS, Linux","SARIF","Database creation and custom queries require expertise."],
  ["Bandit","Static analysis","Find common security issues in Python source code.","PyCQA/bandit","python sast source security","Offline","Local","Easy","CLI","Windows, macOS, Linux","JSON, SARIF, text","Language-specific and pattern-based."],
  ["Brakeman","Static analysis","Scan Ruby on Rails applications for common security weaknesses.","presidentbeef/brakeman","ruby rails sast security","Offline","Local","Easy","CLI","Windows, macOS, Linux","JSON, SARIF, HTML","Focused specifically on Rails."],
  ["SpotBugs","Static analysis","Analyse Java bytecode for bug patterns, with security plugins available.","spotbugs/spotbugs","java bytecode static analysis bugs","Offline","Local","Moderate","CLI + build plugin","Windows, macOS, Linux","XML, HTML","Security depth depends on plugins and configuration."],
  ["OWASP Dependency-Check","Dependency analysis","Identify known vulnerable dependencies in application projects.","dependency-check/DependencyCheck","sca dependency cve software composition","Offline","Mixed","Moderate","CLI + build plugin","Windows, macOS, Linux","HTML, JSON, SARIF","Package-to-CVE matching can produce false positives."],
  ["OSV-Scanner","Dependency analysis","Scan lockfiles, SBOMs and source trees against the OSV database.","google/osv-scanner","dependency osv vulnerability sbom","Offline","Mixed","Easy","CLI","Windows, macOS, Linux","JSON, SARIF","Coverage follows ecosystem and advisory data."],
  ["Dependency-Track","Dependency analysis","Continuously analyse SBOMs and component risk in a central platform.","DependencyTrack/dependency-track","sbom component vulnerability risk","Active","Mixed","Advanced","Web platform","Platform independent","Dashboards, API","Requires hosting and disciplined SBOM ingestion."],
  ["ZAP","Web application testing","Intercept, crawl and assess authorised web applications.","zaproxy/zaproxy","dast proxy web scan owasp","Active","Local","Moderate","Desktop + CLI","Windows, macOS, Linux","HTML, JSON, alerts","Automated findings need validation; active scans can affect targets."],
  ["Nuclei","Template-based scanning","Run signed or reviewed templates against explicitly authorised targets.","projectdiscovery/nuclei","template vulnerability scan web network","Active","Local","Moderate","CLI","Windows, macOS, Linux","JSON, SARIF","Templates generate active requests and vary in safety."],
  ["Nikto","Web application testing","Check web servers for known dangerous files and configuration issues.","sullo/nikto","web server scanner misconfiguration","Active","Local","Easy","CLI","Windows, macOS, Linux","Text, XML","Noisy checks can trigger controls."],
  ["testssl.sh","TLS assessment","Assess TLS protocol, cipher and certificate configuration on authorised services.","testssl/testssl.sh","tls ssl cipher certificate server","Active","Local","Easy","CLI","Linux, macOS","JSON, HTML, CSV","Directly probes the target service."],
  ["sslyze","TLS assessment","Analyse TLS endpoints and cryptographic configuration programmatically.","nabla-c0d3/sslyze","tls certificate cipher scan","Active","Local","Easy","CLI + library","Windows, macOS, Linux","JSON, text","Directly connects to assessed endpoints."],
  ["Ghidra","Reverse engineering","Analyse compiled software with disassembly and decompilation.","NationalSecurityAgency/ghidra","binary malware reverse engineering decompiler","Offline","Local","Moderate","Desktop","Windows, macOS, Linux","Projects, exports","Complex binaries still demand specialist expertise."],
  ["radare2","Reverse engineering","Inspect, debug and automate binary analysis from a command line.","radareorg/radare2","binary reverse engineering debugger","Offline","Local","Advanced","CLI","Windows, macOS, Linux","Text, graphs","Powerful interface has a steep learning curve."],
  ["Cutter","Reverse engineering","Provide a graphical reverse-engineering interface powered by Rizin.","rizinorg/cutter","binary reverse engineering gui decompiler","Offline","Local","Moderate","Desktop","Windows, macOS, Linux","Projects, graphs","Plugin and decompiler capabilities vary."],
  ["Rizin","Reverse engineering","Analyse binaries through a scriptable reverse-engineering framework.","rizinorg/rizin","binary reverse engineering disassembler","Offline","Local","Advanced","CLI + library","Windows, macOS, Linux","Text, graphs","Requires reverse-engineering knowledge."],
  ["CAPA","Malware analysis","Identify capabilities in executable files using human-readable rules.","mandiant/capa","malware capability binary rules","Offline","Local","Moderate","CLI","Windows, macOS, Linux","JSON, text","Packed or unusual samples can reduce visibility."],
  ["FLOSS","Malware analysis","Extract and decode obfuscated strings from malware binaries.","mandiant/flare-floss","malware strings obfuscation decode","Offline","Local","Moderate","CLI","Windows, macOS, Linux","Strings, JSON","Output requires contextual analysis."],
  ["Cuckoo Sandbox","Malware sandboxing","Execute suspicious files in an instrumented analysis environment.","cuckoosandbox/cuckoo","malware sandbox dynamic analysis","Active","Local","Advanced","Web platform","Linux","Reports, artefacts","Untrusted code requires strong isolation and network control."],
  ["CAPE","Malware sandboxing","Automate malware configuration extraction and behavioural analysis.","kevoreilly/CAPEv2","malware sandbox config extraction","Active","Local","Advanced","Web platform","Linux","Reports, artefacts","Deployment and containment are operationally demanding."],
  ["MISP","Threat intelligence","Store, correlate and exchange structured threat intelligence.","MISP/MISP","cti ioc sharing correlation stix","Active","Mixed","Advanced","Web platform","Linux","Events, feeds, STIX","Taxonomy and sharing controls require governance."],
  ["OpenCTI","Threat intelligence","Model and analyse cyber-threat knowledge using structured relationships.","OpenCTI-Platform/opencti","cti stix graph threat intelligence","Active","Mixed","Advanced","Web platform","Platform independent","STIX, graph, reports","Connector ecosystem and infrastructure require maintenance."],
  ["TheHive","Case management","Coordinate security investigations, tasks and observable analysis.","TheHive-Project/TheHive","incident case management soc observables","Active","Mixed","Advanced","Web platform","Platform independent","Cases, reports","Sensitive case data requires access controls and backups."],
  ["Cortex","Observable analysis","Run analyzers and responders against observables from investigation workflows.","TheHive-Project/Cortex","observable analyzer responder threat intel","Active","External","Advanced","Web platform","Linux","Analyzer reports","Analyzers may disclose observables to third parties."],
  ["IntelMQ","Threat intelligence","Collect, normalise and route security event feeds through pipelines.","certtools/intelmq","feed cti incident normalization automation","Active","Mixed","Advanced","Service","Linux","Normalised events","Feed quality and parser maintenance are ongoing concerns."],
  ["Yeti","Threat intelligence","Organise indicators, observables and threat knowledge for analysis.","yeti-platform/yeti","cti indicators observables threat actors","Active","Mixed","Advanced","Web platform","Linux","Entities, indicators","Requires infrastructure and data governance."],
  ["ThreatIngestor","Threat intelligence","Extract indicators from sources and send them to configured outputs.","InQuest/ThreatIngestor","ioc extract rss twitter feeds","Active","External","Moderate","CLI + service","Windows, macOS, Linux","Indicators","Extraction does not establish maliciousness."],
  ["STIX2 Python","Threat intelligence","Create, parse and validate STIX 2 cyber-threat objects in Python.","oasis-open/cti-python-stix2","stix cti python objects","Offline","Local","Moderate","Python library","Windows, macOS, Linux","STIX JSON","Does not provide an analyst interface."],
  ["Prowler","Cloud security","Assess AWS, Azure, Google Cloud and Kubernetes security configuration.","prowler-cloud/prowler","aws azure gcp kubernetes audit cis","Active","Local","Moderate","CLI","Windows, macOS, Linux","HTML, JSON, CSV","Requires cloud credentials and can generate many API calls."],
  ["Scout Suite","Cloud security","Review multi-cloud security posture through API-based configuration collection.","nccgroup/ScoutSuite","aws azure gcp cloud audit","Active","Local","Moderate","CLI","Windows, macOS, Linux","HTML report","Read-only credentials still expose sensitive configuration."],
  ["Cloud Custodian","Cloud security","Enforce cloud governance and security policies as code.","cloud-custodian/cloud-custodian","cloud policy aws azure gcp governance","Active","Local","Advanced","CLI + service","Windows, macOS, Linux","Policy actions, reports","Remediation policies can change or delete resources."],
  ["Cloudsplaining","Cloud security","Analyse AWS IAM policies for excessive and risky permissions.","salesforce/cloudsplaining","aws iam least privilege policy","Offline","Local","Moderate","CLI","Windows, macOS, Linux","HTML, JSON","Analysis depends on supplied IAM data and context."],
  ["Cartography","Cloud security","Consolidate infrastructure assets and relationships into a graph.","lyft/cartography","cloud asset graph aws gcp inventory","Active","Mixed","Advanced","Service","Linux","Graph database","Collection needs broad read access and data protection."],
  ["CloudQuery","Cloud security","Extract cloud asset configuration into queryable data stores.","cloudquery/cloudquery","cloud asset inventory sql aws azure gcp","Active","Mixed","Advanced","CLI + platform","Windows, macOS, Linux","Tables","Destinations may create additional data exposure."],
  ["kube-bench","Kubernetes security","Check Kubernetes nodes against CIS benchmark controls.","aquasecurity/kube-bench","kubernetes cis benchmark audit","Active","Local","Moderate","CLI","Linux","JSON, text","Benchmark compliance is not complete security assurance."],
  ["kube-hunter","Kubernetes security","Probe Kubernetes environments for common security weaknesses.","aquasecurity/kube-hunter","kubernetes penetration testing discovery","Active","Local","Moderate","CLI","Linux","Findings","Active mode can affect or alert the cluster."],
  ["Kubescape","Kubernetes security","Assess Kubernetes manifests and clusters against security frameworks.","kubescape/kubescape","kubernetes posture misconfiguration compliance","Active","Mixed","Moderate","CLI + platform","Windows, macOS, Linux","JSON, SARIF","Hosted features alter the data path."],
  ["Checkov","Infrastructure security","Scan infrastructure-as-code for misconfiguration and policy violations.","bridgecrewio/checkov","iac terraform cloudformation kubernetes scan","Offline","Mixed","Easy","CLI","Windows, macOS, Linux","SARIF, JSON","Framework coverage and hosted options vary."],
  ["tfsec","Infrastructure security","Find security misconfigurations in Terraform code.","aquasecurity/tfsec","terraform iac security scan","Offline","Local","Easy","CLI","Windows, macOS, Linux","SARIF, JSON","Static configuration lacks runtime context."],
  ["Conftest","Policy as code","Test structured configuration using Open Policy Agent policies.","open-policy-agent/conftest","opa policy configuration iac","Offline","Local","Moderate","CLI","Windows, macOS, Linux","Test results","Policy quality is entirely user-defined."],
  ["Wazuh","Security monitoring","Collect endpoint and log telemetry for detection, integrity monitoring and compliance.","wazuh/wazuh","siem xdr endpoint log monitoring","Active","Mixed","Advanced","Server + agent","Windows, macOS, Linux","Alerts, dashboards","Deployment and tuning require sustained operations."],
  ["Security Onion","Security monitoring","Deploy an integrated platform for network security monitoring and investigation.","Security-Onion-Solutions/securityonion","soc network zeek suricata elastic","Passive","Local","Advanced","Platform","Linux","Alerts, cases, PCAP","Substantial infrastructure and operational expertise required."],
  ["Shuffle","Security automation","Build and run security automation workflows with integrations.","Shuffle/Shuffle","soar automation workflow security","Active","Mixed","Advanced","Web platform","Platform independent","Workflow results","Automations can perform consequential actions."],
  ["Caldera","Adversary emulation","Automate authorised adversary emulation using ATT&CK-aligned abilities.","mitre/caldera","adversary emulation attack purple team","Active","Local","Advanced","Web platform + agents","Windows, macOS, Linux","Operation reports","Agents and abilities can disrupt systems and trigger controls."],
  ["Atomic Red Team","Detection validation","Run small ATT&CK-mapped tests to validate defensive visibility.","redcanaryco/atomic-red-team","attack tests detection validation purple","Active","Local","Advanced","Tests","Windows, macOS, Linux","Execution logs","Tests can alter systems and must be individually reviewed."],
  ["Stratus Red Team","Cloud detection validation","Emulate granular cloud attack techniques for defensive testing.","DataDog/stratus-red-team","aws azure gcp attack emulation detection","Active","Local","Advanced","CLI","Windows, macOS, Linux","Execution logs","Creates real cloud activity and sometimes resources."],
  ["Infection Monkey","Breach simulation","Test segmentation and attack paths in controlled environments.","guardicore/monkey","breach simulation lateral movement network","Active","Local","Advanced","Server + agent","Windows, Linux","Reports","Designed to propagate; strict authorisation and isolation are essential."],
];

export const tools: Tool[] = rows.map(([name, category, summary, slug, keywords, interaction, data, setup, delivery, platformText, output, limitation]) => ({
  name, category, summary, repo: `https://github.com/${slug}`, keywords, interaction, data, setup, delivery,
  platforms: platformText.split(", "), output, limitation, evidence: "Repository verified", reviewed: "2026-08-21",
}));

export const categories = Array.from(new Set(tools.map((tool) => tool.category))).sort();
export const platforms = Array.from(new Set(tools.flatMap((tool) => tool.platforms))).sort();
